### ISSUE TITLE
Informal Dinner at Song Fa Bah Kut Teh Chinatown Point

### ISSUE THREAD

**Issue by tgxworld** [reddotrubyconf/rdrc2016#40]
Hi all! 

We will like to bring you to China Town to try out one of our local favourites "pork ribs soup". 

As majority of the speakers are staying at Naumi Liora, I'll be at the lobby at 6pm to bring everyone over from there. The walk to Chinatown point is about 10mins long. As the restaurant does not take reservations, some queuing time is expected but it'll be worth it :)

If you'll like to join us, please drop a _:+1: comment_ here so that we can make the necessary arrangements :)

**Comment by tgxworld** [comment]
Do note that the restaurant is not halal certified and does not provide vegetarian options. However, You're still invited to join us and I'll bring you guys around Chinatown point to look for suitable options.

**Comment by tgxworld** [comment]
opps :+1: as a new comment please :)

**Comment by rkh** [comment]
Will there be meatless options?

**Comment by tgxworld** [comment]
@rkh Unfortunately not :(

**Comment by hsbt** [comment]
:+1: I will join it.

**Comment by davydovanton** [comment]
I'll join too :star2:

**Comment by tenderlove** [comment]
:+1:

**Comment by morizyun** [comment]
Thank you so much. I will join it too 👍

**Comment by JuanitoFatas** [comment]
👍🏻:+1:👍🏻

**Comment by olejrosendahl** [comment]
👍

**Comment by nay** [comment]
Thank you! I will join it too 👍

**Comment by chancancode** [comment]
:+1:

**Comment by aquajach** [comment]
I'm coming too 👍

**Comment by matthewd** [comment]
👍

**Comment by Drenmi** [comment]
👍

**Comment by v0dro** [comment]
:+1:

**Comment by skatkov** [comment]
Will join

**Comment by janko-m** [comment]
I will join as well 👍

**Comment by ghprince** [comment]
👍

**Comment by hanmd82** [comment]
:+1:

**Comment by thenglee** [comment]
👍

**Comment by keithrbennett** [comment]
I'm 90% sure, but would like to meet you at the restaurant.  Can you say which one it is?

Also, I'm getting over a bout of food poisoning last Saturday night that had me in the hospital all night and am still not 100% recovered stomach wise.  Can you describe the dish and whether there might be tamer options if necessary (such as chicken noodle soup, non-spicy rice/noodle dishes)?
